# vis
# /vis/open OGLIQt
# /vis/drawVolume
# /vis/viewer/flush
# /tracking/storeTrajectory             1
# /vis/scene/add/trajectories
# /vis/scene/endOfEventAction           accumulate

#=====================================================
# VERBOSITY
#=====================================================

/control/execute mac/verbose.mac

#=====================================================
# VISUALISATION
#=====================================================

/control/execute mac/visu.mac

# =====================================================
# GEOMETRY
# =====================================================

/gate/geometry/setMaterialDatabase data/GateMaterials.db

# WORLD
/gate/world/setMaterial            Air
/gate/world/geometry/setXLength    1.0 m
/gate/world/geometry/setYLength    1.0 m
/gate/world/geometry/setZLength    1.0 m
/gate/world/vis/setVisible 1

# LINAC HEAD
# World origin is in the center of the beam e- source (not the real
# isocenter of the gantry room)
/gate/geometry/setMaterialDatabase data/LinacMaterials.db
/control/execute mac/linac_head.mac

# =====================================================
# PHYSICS
# =====================================================

# /gate/physics/addPhysicsList emstandard_opt3
/gate/physics/addPhysicsList QGSP_BIC_HP


# ----------------------------------------------------
# the following actor regularly store the current number of
# event/track/step in a file

/gate/actor/addActor               SimulationStatisticActor stat
/gate/actor/stat/save              output/output-writePhS-stat.txt
/gate/actor/stat/saveEveryNSeconds 20

# ----------------------------------------------------
# Phase space storage (a PhS for gamma, another for e-)

/gate/actor/addActor                         PhaseSpaceActor phspLinac
/gate/actor/phspLinac/attachTo                   linac
/gate/actor/phspLinac/save 	                     output/phspLinac.IAEAheader
/gate/actor/phspLinac/useVolumeFrame             true
/gate/actor/phspLinac/enableZPosition            true
/gate/actor/phspLinac/storeOutgoingParticles true
/gate/actor/phspLinac/addFilter                  particleFilter
/gate/actor/phspLinac/particleFilter/addParticle neutron

#=====================================================
# INITIALISATION
#=====================================================

/gate/run/initialize

# Bremsstrahlung splitting : generate 100 photon (if below 100 MeV) with weight 1/100
# /process/em/setSecBiasing eBrem target 100 100 MeV

#=====================================================
# BEAMS
#=====================================================

/gate/source/addSource                mybeam gps
/gate/source/mybeam/gps/particle      e-
/gate/source/mybeam/gps/pos/type      Beam
/gate/source/mybeam/gps/pos/rot1      0 1 0
/gate/source/mybeam/gps/pos/rot2      1 0 0
/gate/source/mybeam/gps/pos/shape     Circle
/gate/source/mybeam/gps/pos/centre    0. 0. 0.6 mm
/gate/source/mybeam/gps/pos/sigma_x   1.274 mm
/gate/source/mybeam/gps/pos/sigma_y   1.274 mm
/gate/source/mybeam/gps/ang/rot1      1 0 0
/gate/source/mybeam/gps/ang/rot2      0 1 0
/gate/source/mybeam/gps/ang/type      beam1d
/gate/source/mybeam/gps/ang/sigma_r   0 deg
/gate/source/mybeam/gps/ene/type      Gauss
/gate/source/mybeam/gps/ene/mono      18 MeV
/gate/source/mybeam/gps/ene/sigma     0.077 MeV
/gate/source/mybeam/gps/direction     0 0 -1

#=====================================================
# START BEAMS
#=====================================================

/gate/random/setEngineName MersenneTwister
/gate/random/setEngineSeed auto
/gate/application/noGlobalOutput

#/tracking/verbose 2

/gate/application/setTotalNumberOfPrimaries 10000000
/gate/application/start
